version: "3.8"

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-app:
    build: .
    container_name: springboot-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend-network
    volumes:
      - .:/app
    command: ["mvn", "spring-boot:run"]

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
